version: "3.7"

services:
  redis:
    container_name: "Redis"
    image: redis:6.2-alpine
    restart: unless-stopped
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks: 
      - services
  backend:
    container_name: "BackendAPI"
    ports: 
      - "8080:8080"
    build: ./Backend
    networks: 
      - services
  bot:
    container_name: "DiscordBot"
    build: ./Bot
    networks: 
      - services

volumes:
  redis_data:
    driver: local

networks: 
  services: 